name: Development-Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ️
        uses: actions/checkout@v2.3.1
      - name: Build Javadocs
        run: |
          echo "Building javadocs with maven"
          ./mvn javadoc
          echo "Moving to javadocs directory:"
          cd build/docs/javadoc/
          echo "Creating .nojekyll to have Github pages deploy html as is:"
          touch .nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/docs/javadoc/ # The folder the action should deploy.
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.repository}}
          separator: "/"
      - name: Build
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "D-x-Z"
          embed-title: "${{ github.actor }} pushed an update for ${{ steps.split.outputs._1 }}"
          avatar-url: "https://github.com/D-x-Z.png"
          embed-color: "65280"
          embed-author-name: "${{ github.actor }}"
          embed-author-url: "https://github.com/${{ github.actor }}"
          embed-author-icon-url: "https://github.com/${{ github.actor }}.png"
          embed-footer-text: "Build #${{github.run_number}} passed and waiting to be updated"
          embed-footer-icon-url: "https://i.imgur.com/D5KVghH.png"
          embed-description: |
            ${{ github.event.head_commit.message }}